version: '3.7'

services:
  photobook:
    build: .
    image: photobook-render:latest
    container_name: ${NAME}
    command: gunicorn --bind 0.0.0.0:5000 wsgi:app --workers 1 --threads 1 -k gthread --timeout 180
    restart: always
    environment:
      - DOMAINS_DICT_PATH=domains.json
      - APP_ENV="production"
    volumes:
      - ~/tmp/book/:~/tmp/book/
    ports:
      - "8070:5000"