domains = {
  'pechat.photo': '/var/www/demonstration/data/www/pechat.photo/',
  'casy.com.ua': '/var/www/casycomua/data/www/casy.com.ua/',
  'digitalfoto.pp.ua': '/var/www/digitalfotoua/data/www/digitalfoto.pp.ua/',
  'gift-photo.com': '/var/www/admin/data/www/gift-photo.com/',
  'foto124.ru': '/var/www/foto124/data/www/foto124.ru/',
  'memory-moments.online': '/var/www/borovodessa/data/www/memory-moments.online/',
  'online.photolier.ru': '/var/www/photolier/data/www/online.photolier.ru/',
  'pechatfotoonline.ru': '/var/www/pechatfotoonline/data/www/pechatfotoonline.ru/',
  'photo-mich.ru': '/var/www/photomich/data/www/photo-mich.ru/',
  'photopechat23.ru': '/var/www/urakrasnodar/data/www/photopechat23.ru/',
  'xn--80aj0aafqej6a4c.xn--80asehdb': '/var/www/admin/data/www/xn--80aj0aafqej6a4c.xn--80asehdb/',
  'konigfoto.ru': '/var/www/konigfoto/data/www/konigfoto.ru/',
  'color-foto.ru': '/var/www/antares/data/www/color-foto.ru/',
  '2kadra-foto.ru': '/var/www/2kadra/data/www/2kadra-foto.ru/',
  'fotoprintperm.ru': '/var/www/fotoprintperm/data/www/fotoprintperm.ru/',
  'xn--h1aahfheaf3as4j.xn--p1ai': '/var/www/alex/data/www/xn--h1aahfheaf3as4j.xn--p1ai/',
  'xn--80aaaebe5avxvsy.xn--p1ai': '/var/www/tambov/data/www/xn--80aaaebe5avxvsy.xn--p1ai/',
  'fotoprint60.ru': '/var/www/fotoprint60/data/www/fotoprint60.ru/',
  'xn--24-plciib4bya.xn--p1ai': '/var/www/ilshat/data/www/xn--24-plciib4bya.xn--p1ai/',
  'foto-book.online': '/var/www/fotokniga/data/www/foto-book.online/',
  'birfotomir.ru': '/var/www/birfotomir/data/www/birfotomir.ru/',
  'fotodrug53.ru': '/var/www/fotodrug53/data/www/fotodrug53.ru/',
  'pechat63.ru': '/var/www/nemirov/data/www/pechat63.ru/',
  'aitifoto.kz': '/var/www/aitifoto/data/www/aitifoto.kz/',
  'fotomig76.ru': '/var/www/fotomig76/data/www/fotomig76.ru/',
  'xn----jtbybapjely.xn--p1ai': '/var/www/fotocenter/data/www/xn----jtbybapjely.xn--p1ai/',
  'tulaprint.com': '/var/www/tulaprint/data/www/tulaprint.com/',
  'photopro.od.ua': '/var/www/photopro.od.ua/data/www/photopro.od.ua/',
  'fotonadom.su': '/var/www/fotonadom/data/www/fotonadom.su/',
  'mispa.lv': '/var/www/mispa/data/www/mispa.lv/',

}
